const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const moduleAt=name=>import('data:text/javascript;base64,'+fs.readFileSync(path.join(__dirname,'../www/js',name)).toString('base64'));
(async()=>{
 const m=await moduleAt('garanci-workspace.js'),s=await moduleAt('service-model.js');
 assert.equal(m.repairMillis({date:'13/09/2026'}),new Date(2026,8,13).getTime());assert.equal(m.repairMillis({date:'10/09/2026'}),new Date(2026,8,10).getTime());
 const cards=[{id:'w',saleId:'sale',saleType:'storeSale',customerName:'A',items:[{name:'K5',serialNumber:'111',sourceItemIndex:0}]},{id:'legacy',saleId:'other',saleType:'storeSale',customerName:'A',items:[{name:'Same'}]}];
 assert.equal(m.matchWarrantyForMachine(cards,{saleId:'sale',saleType:'storeSale',itemIndex:1,name:'WD3',serialNumber:'222',customerName:'A'}),null);
 assert.equal(m.matchWarrantyForMachine(cards,{saleId:'sale',saleType:'storeSale',itemIndex:0,name:'K5',serialNumber:'111',customerName:'A'}).id,'w');
 assert.equal(m.matchWarrantyForMachine(cards,{saleId:'wrong',saleType:'storeSale',itemIndex:0,name:'K5',serialNumber:'111',customerName:'A'}),null);
 assert.equal(m.matchWarrantyForMachine(cards,{saleId:'other',saleType:'storeSale',itemIndex:1,name:'Same',customerName:'A',siblingItems:[{name:'Same'},{name:'Same'}]}),null);
 assert.equal(m.matchWarrantyForMachine(cards,{saleId:'other',saleType:'storeSale',itemIndex:0,name:'Same',customerName:'A',siblingItems:[{name:'Same'}]}).id,'legacy');
 const now=new Date(2026,8,10,12).getTime();const attention=m.getAttentionItems([{id:'closed',status:'completed',promisedBy:'2020-01-01'},{id:'late',status:'received',promisedBy:'2026-09-09'},{id:'today',status:'in_progress',tech:'T',promisedBy:'2026-09-10'}],now);assert.deepEqual(attention.map(x=>x.ticket.id),['late']);
 const before={notes:'old',tech:'T',timeline:[1]},changes=s.changedFields(before,{notes:'new',tech:'T'});assert.deepEqual(changes,{notes:'new'});s.assertNoConflicts(before,{...before,timeline:[1,2]},changes);assert.throws(()=>s.assertNoConflicts(before,{...before,notes:'concurrent'},changes));
 assert.throws(()=>s.normalizeParts([{name:'',quantity:1,status:'needed'}]));assert.throws(()=>s.normalizeParts([{name:'Motor',quantity:1.5,status:'ordered'}]));assert.throws(()=>s.normalizeCosts({parts:-1}));assert.equal(s.normalizeCosts({parts:12.345}).parts,12.35);
 const directory=m.buildMachineDirectory([{id:'sale',collectionName:'storeSales',clientName:'A',items:[{name:'K5',serialNumber:'111'},{name:'WD3',serialNumber:'222'}]}],cards);assert.equal(directory.filter(x=>x.saleId==='sale').length,2);
 const manualCard={id:'manual',saleType:'manual',customerName:'A',items:[{name:'K5',serialNumber:'',sourceItemIndex:null},{name:'K5',serialNumber:'',sourceItemIndex:null}]};
 const manualMachines=m.buildMachineDirectory([], [manualCard]);
 const manualTicket={customerName:'A',productName:'K5',serialNumber:'',warrantyCardId:'manual',warrantyCardItemIndex:1};
 const manualMatches=m.getWarrantyMatches([manualCard],manualTicket);
 assert.equal(manualMatches.length,1);assert.equal(manualMatches[0].itemIndex,1);
 assert.equal(m.ticketMatchesMachine(manualTicket,manualMachines[0],m.getWarrantyMatches([manualCard],manualMachines[0])),false);
 assert.equal(m.ticketMatchesMachine(manualTicket,manualMachines[1],m.getWarrantyMatches([manualCard],manualMachines[1])),true);
 assert.equal(m.getWarrantyMatches([manualCard],{customerName:'A',productName:'K5',warrantyCardId:'manual'}).length,0);
 const singleManual={...manualCard,id:'single-manual',items:[manualCard.items[0]]};
 assert.equal(m.getWarrantyMatches([singleManual],{customerName:'A',productName:'K5',warrantyCardId:singleManual.id})[0].itemIndex,0);
 assert.equal(m.getWarrantyMatches([singleManual],{customerName:'B',warrantyCardId:singleManual.id}).length,0);
 assert.equal(m.getWarrantyMatches(cards,{saleId:'wrong',saleType:'storeSale',customerName:'A',warrantyCardId:'w',warrantyCardItemIndex:0}).length,0);
 console.log('PASS: per-item coverage, sale boundaries, ambiguous names, deadlines, concurrent edits, part/cost validation, directory');
})().catch(error=>{console.error(error);process.exitCode=1;});
