const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),www=path.join(root,'www'),out=path.join(root,'artifacts','qa');fs.mkdirSync(out,{recursive:true});
const sdk=fs.readFileSync(path.join(__dirname,'firebase-fixture.js'),'utf8');
const now=Date.now(),ts=days=>({$ms:now+days*86400000});
const seed={
 'customers/c1':{name:'Klient Test',phone:'0690000000',city:'Tiranë',nipt:'TEST',address:'Rruga, Tirane, Albania'},
 'storeSales/s1':{clientName:'Klient Test',invoiceNumber:'TEST-001',timestamp:ts(-20),items:[{name:'Kärcher K5',serialNumber:'K5-TEST',quantity:1,price:250},{name:'Kärcher WD3',serialNumber:'WD3-TEST',quantity:3,price:100}]},
 'onlineOrders/s2':{clientName:'Klient Test',invoiceNumber:'TEST-002',timestamp:ts(-10),items:[{name:'Pompë test',serialNumber:'P-TEST',quantity:4,price:80}]},
 'warrantyCards/w1':{saleId:'s1',saleType:'storeSale',customerName:'Klient Test',certNo:'GAR-TEST-001',createdAt:ts(-10),purchaseDate:ts(-20),warrantyUntil:ts(20),items:[{name:'Kärcher K5',serialNumber:'K5-TEST',sourceItemIndex:0}],repairs:[]},
 'warrantyCards/w2':{saleType:'manual',customerName:'Klient Manual',certNo:'GAR-TEST-002',createdAt:ts(-10),warrantyUntil:ts(300),items:[{name:'Makina manuale',serialNumber:'M-TEST'}]},
 'serviceTickets/t1':{claimNo:'KRK-TEST-001',customerName:'Klient Test',customerPhone:'0690000000',productName:'Kärcher K5',serialNumber:'K5-TEST',linkedSaleId:'s1',linkedSaleType:'storeSale',linkedItemIndex:0,warrantyCardId:'w1',issueDescription:'Nuk jep presion',status:'received',priority:'Urgjent',mode:'Në servis',tech:'',notes:'',createdAt:ts(-8),scheduledAt:ts(0),promisedBy:'2020-01-01',timeline:[{title:'U regjistrua',when:'01.09.2026',who:'Test'}]},
 'serviceTickets/t2':{claimNo:'KRK-TEST-002',customerName:'Klient Test',productName:'Pompë test',serialNumber:'P-TEST',linkedSaleId:'s2',linkedSaleType:'onlineOrder',issueDescription:'Nuk ndizet',status:'waiting_parts',priority:'Normal',mode:'Në terren',tech:'Teknik Test',createdAt:ts(-3),parts:[{name:'Motor',quantity:1,status:'ordered',expectedOn:'2020-01-01'}],repairCosts:{parts:50,labour:20,supplierClaim:50,supplierReceived:10,currency:'EUR'},timeline:[]},
 'serviceTickets/t3':{claimNo:'KRK-TEST-003',customerName:'Klient Test',productName:'Kärcher WD3',serialNumber:'WD3-TEST',status:'completed',createdAt:ts(-5),timeline:[]}
};
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const target=path.resolve(www,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!target.startsWith(www+path.sep)){res.writeHead(403).end();return;}fs.readFile(target,(error,body)=>{res.writeHead(error?404:200,{'Content-Type':types[path.extname(target)]||'application/octet-stream'});res.end(error?'Missing':body);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1280,height:900}});
 await context.addInitScript(value=>{window.__seed=value;},seed);
 await context.route('**/*',route=>{const url=route.request().url();if(url.startsWith('https://www.gstatic.com/firebasejs/'))return route.fulfill({status:200,contentType:'text/javascript',body:sdk});if(url.startsWith(base)||url.startsWith('data:'))return route.continue();return route.abort();});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{errors.push('Unexpected dialog: '+d.message());d.dismiss();});
 const wait=()=>page.waitForFunction(()=>document.querySelector('.dg-sidebar')&&!document.querySelector('#page-error:not([hidden])'));
 const noWrites=async()=>assert.equal(await page.evaluate(()=>window.__mock.writes.length),0,'Read-only view wrote data');
 const report=[];
 try{
  for(const name of ['index','pending','machines','schedule','analytics','issue','claim']){
   await page.goto(`${base}/${name}.html`);await wait();await page.waitForTimeout(250);await noWrites();
   if(name==='index'){await page.waitForFunction(()=>document.getElementById('open-count').textContent==='2');assert.equal(await page.locator('#parts-count').innerText(),'1');}
   if(name==='pending'){await page.locator('#search-input').fill('K5-TEST');assert.equal(await page.locator('.dg-job').count(),1);await page.locator('#search-input').fill('');}
   await page.screenshot({path:path.join(out,`${name}-desktop.png`),fullPage:true});
   await page.setViewportSize({width:800,height:700});await page.waitForTimeout(50);
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`${name} overflows at minimum app width`);
   await page.screenshot({path:path.join(out,`${name}-compact.png`),fullPage:true});await page.setViewportSize({width:1280,height:900});report.push(`${name}: rendered, read only, compact layout`);
  }
  await page.goto(`${base}/pending-detail.html?id=t1`);await page.locator('#service-form').waitFor();await noWrites();
  await page.screenshot({path:path.join(out,'detail-desktop.png'),fullPage:true});
  await page.locator('#tech').fill('Teknik i ri');await page.locator('#status').selectOption('in_progress');await page.locator('#cost-parts').fill('25.50');await page.locator('#cost-labour').fill('10');
  await page.locator('#save-service').click();await page.getByRole('dialog').waitFor();await noWrites();
  await page.evaluate(()=>window.__mock.records['serviceTickets/t1'].timeline.push({title:'Ndryshim nga kolegu',when:'sot',who:'Koleg'}));
  await page.getByRole('dialog').getByRole('button',{name:'Ruaj ndryshimet',exact:true}).click();await page.waitForFunction(()=>document.getElementById('save-status')?.textContent.includes('ruajtën'));
  const saved=await page.evaluate(()=>window.__mock.records['serviceTickets/t1']);assert.equal(saved.tech,'Teknik i ri');assert.equal(saved.repairCosts.parts,25.5);assert(saved.timeline.some(t=>t.title==='Ndryshim nga kolegu'));
  await page.locator('#status').selectOption('completed');await page.locator('#save-service').click();await page.getByRole('dialog').getByRole('button',{name:'Ruaj ndryshimet',exact:true}).click();await page.waitForFunction(()=>window.__mock.records['warrantyCards/w1'].repairs.length===1);
  assert.equal(await page.evaluate(()=>window.__mock.records['warrantyCards/w1'].repairs[0].ticketId),'t1');report.push('Service: confirmation before writes, costs saved, concurrent timeline preserved, completion synced');
  await page.locator('#status').selectOption('in_progress');await page.locator('#save-service').click();await page.getByRole('dialog').getByRole('button',{name:'Ruaj ndryshimet',exact:true}).click();await page.waitForFunction(()=>document.getElementById('save-status')?.textContent.includes('ruajtën'));
  await page.locator('#status').selectOption('completed');await page.locator('#save-service').click();await page.getByRole('dialog').getByRole('button',{name:'Ruaj ndryshimet',exact:true}).click();await page.waitForFunction(()=>document.getElementById('save-status')?.textContent.includes('ruajtën'));assert.equal(await page.evaluate(()=>window.__mock.records['warrantyCards/w1'].repairs.length),1);report.push('Service: reopening and completing does not duplicate repair history');
  await page.locator('#photo-input').setInputFiles({name:'intake-fixture.png',mimeType:'image/png',buffer:fs.readFileSync(path.join(www,'assets','garanci-logo.png'))});await page.waitForFunction(()=>!document.getElementById('upload-photos').disabled);const writesBeforePhotos=await page.evaluate(()=>window.__mock.writes.length);await page.locator('#upload-photos').click();await page.getByRole('dialog').waitFor();assert.equal(await page.evaluate(()=>window.__mock.writes.length),writesBeforePhotos);await page.getByRole('dialog').getByRole('button',{name:'Ruaj 1 foto',exact:true}).click();await page.waitForFunction(()=>window.__mock.records['serviceTickets/t1'].photoCount===1);assert.equal(await page.locator('#saved-photos img').count(),1);const photo=await page.evaluate(()=>Object.entries(window.__mock.records).find(([key])=>key.startsWith('serviceTickets/t1/photos/'))[1]);assert(photo.dataUrl.startsWith('data:image/jpeg;base64,'));assert(photo.dataUrl.length<=280000);report.push('Intake photos: preview, confirmation, JPEG compression and atomic photo count');
  await page.goto(`${base}/pending-detail.html?id=t1`);await page.locator('#service-form').waitFor();await page.locator('#tech').fill('Conflicting');await page.locator('#save-service').click();await page.getByRole('dialog').waitFor();await page.evaluate(()=>window.__mock.records['serviceTickets/t1'].tech='Concurrent');await page.getByRole('dialog').getByRole('button',{name:'Ruaj ndryshimet',exact:true}).click();await page.locator('#page-error').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>window.__mock.records['serviceTickets/t1'].tech),'Concurrent');await noWrites();report.push('Service: concurrent field changes rejected without writes');
  await page.goto(`${base}/claim.html?saleId=s1&itemIndex=1`);await page.locator('#issue-text').waitFor({state:'visible'});await page.locator('#issue-text').fill('Test fixture only');await page.locator('#submit-claim-btn').click();const dialog=page.getByRole('dialog');await dialog.waitFor();assert((await dialog.innerText()).includes('Pa garanci të lëshuar'));await noWrites();await dialog.getByRole('button',{name:'Konfirmo dhe regjistro',exact:true}).click();await page.waitForFunction(()=>window.__mock.writes.some(w=>w.path.startsWith('serviceTickets/')));const claim=await page.evaluate(()=>window.__mock.writes.find(w=>w.path.startsWith('serviceTickets/')).data);assert.equal(claim.linkedItemIndex,1);assert.equal(claim.serialNumber,'WD3-TEST');assert.equal(claim.warrantyCardId,null);report.push('Claim: multi-item coverage stays specific to selected machine');
  await page.goto(`${base}/index.html`);await wait();await page.locator('[data-ui-settings]').click();await page.locator('[data-ui-accent="gold"]').click();await page.locator('[data-ui-motion="cinematic"]').click();await page.reload();await wait();assert.equal(await page.locator('#app-root').getAttribute('data-accent'),'gold');assert.equal(await page.locator('#app-root').getAttribute('data-motion'),'cinematic');const surface=page.locator('.dg-stat').first(),bounds=await surface.boundingBox();await page.mouse.move(bounds.x+bounds.width*.75,bounds.y+bounds.height*.3);await page.waitForFunction(()=>document.querySelector('.dg-stat').style.getPropertyValue('--dg-rx')!=='');await page.locator('[data-ui-pause]').click();assert(await page.locator('#app-root').evaluate(el=>el.classList.contains('dg-paused')));await page.locator('[data-ui-pause]').click();report.push('Appearance: accent and motion persist, card tilt responds to pointer, pause control works');await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(80);const moving=await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.getTiming().iterations===Infinity).length);assert.equal(moving,0,'Reduced motion should pause continuous animation');report.push('Reduced motion stops continuous animations');
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'ui-results.json'),JSON.stringify({passed:true,checks:report},null,2));console.log(report.join('\n'));
 }catch(error){console.error('Failed at',page.url(),errors);console.error((await page.locator('body').innerText()).slice(0,1800));await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw error;}finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);server.close();process.exitCode=1;});
